spring:
  application:
    name: mscloudgateway
  cloud:
   gateway:
     discovery:
       locator:
         enabled: true
         lower-case-service-id: true

server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka  # isso diz em qual servidor eu quero me registrar

