spring:
  application:
    name: msavaliadorcredito

server:
  port: 0   # instanciara em uma porta aleatoria

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # isso diz em qual servidor eu quero me registrar
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}